shopware:
  feature:
    flags:
      - name: v6.5.0.0
        default: true
        major: true
        toggleable: false
      - name: v6.6.0.0
        default: true
        major: true
        toggleable: false
      - name: v6.7.0.0
        default: true
        major: true
        toggleable: false
      - name: v6.8.0.0
        default: false
        major: true
        toggleable: false
      - name: ADDRESS_SELECTION_REWORK
        default: true
        major: true
        toggleable: false
        description: "Improved and redesigned management of customer addresses in the Storefront"
      - name: DISABLE_VUE_COMPAT
        default: true
        major: true
        toggleable: false
      - name: ACCESSIBILITY_TWEAKS
        default: true
        major: true
        toggleable: true
        description: "Accessibility tweaks (highly recommended)\nAccessibility improvements can alter the HTML and CSS structure of the template.\nThe accessibility improvements will be standard as of v6.7.0"
      - name: TELEMETRY_METRICS
        default: false
        major: false
        toggleable: true
        description: "Experimental! Enable OpenTelemetry metrics"
      - name: cache_rework
        default: false
        major: true
        toggleable: false
        description: "Rework of http cache and store api cache"
      - name: DYNAMIC_ENTITY_EXTENSIONS
        default: false
        major: true
        toggleable: false
        description: "TEMPORARY! disable dynamic entity extensions, as it makes problems during the lifecycle"
      - name: ENABLE_METEOR_COMPONENTS
        default: false
        major: false
        toggleable: false
